crate/crate-sample-apps

php/index.php

see http://stackoverflow.com/questions/3115388/declaration-of-methods-should-be-compatible-with-parent-methods-in-php

fixed error that appears on enabled strict mode

---

java/pom.xml

@ChrisChinchilla this fixes https://github.com/crate/crate-sample-apps/issues/30

added maven central repo to pom file

---

java/src/main/java/io/crate/jdbc/sample/Controller.java
java/src/main/java/io/crate/jdbc/sample/DataProvider.java

* fixed bug in converting `ResultSet` into `List<Map<String, Object>>`
* implemented `/search` endpoint
* improved wording for `400` responses

improved java sample app

---

SPEC.md
tests/test.py

I have been adding some suggestions for corrections of the backend spec while
developing an erlang example app, which comes in a different PR.
let's discuss

some correction suggestions for the backend spec

---

php/README.md
php/index.php
tests/test.py

php ft search

---

README.md

crate 0.54.1 is needed as there was a bug in grouping by arrays.

set the correct crate version

---

java/src/main/java/io/crate/jdbc/sample/Controller.java

Since angular is doing `options` preflight this endpoints needs to be
exist and handled in a separate enpoint.

added options request method to enpoints

---

java/pom.xml

@mikethebeer can you take a look please?

Moved pgjdbc dependency from JIT to Maven

---

README.md
java/README.md
java/documentation.md
java/pom.xml
java/src/main/java/io/crate/jdbc/sample/App.java
java/src/main/java/io/crate/jdbc/sample/Controller.java
java/src/main/java/io/crate/jdbc/sample/DataProvider.java
java/src/main/resources/config.properties

**DO NOT MERGE! WAIT FOR 0.56.0!**

replace the crate jdbc with the pgjdbc driver

---

java/pom.xml
java/src/main/java/io/crate/jdbc/sample/DataProvider.java

updated pom.xml
fixed imports in DataProvider

updated JDBC driver to version 2.1.7 (latest version)

---

java/pom.xml
python/app.py
python/requirements.txt

This fixes CVE-2018-1000656 and CVE-2014-3577

Update apache.httpcomponents and flask

---

.gitignore
nodejs/.gitignore
nodejs/README.rst
nodejs/package.json
nodejs/server.js

Hi there,
this patch makes the Node.js application build and start again. It also needed some further adjustments to conform to the test suite, see 8aea66eb5.
With kind regards,
Andreas.

nodejs-express: Update environment and documentation, and fix HTTP API

---

golang/http.go
golang/interface.go
golang/main.go
golang/postgresql.go

adjusted response codes according to the automated testing application

adjusted response messages according to the specification

---

python-flask/app.py

This somehow slipped through, and should have accompanied 368427dcb already.

python-flask: Add compatibility with Flask 2

---

.github/dependabot.yml
.github/workflows/test-go.yml
.github/workflows/test-java-spark.yml
.gitignore
requirements.txt

A few patches have been submitted by Dependabot, but we don't have any means to validate them, other than doing it manually.
This patch intends to bring in corresponding CI automation, at least for two projects where this works well out of the box.

Add CI configuration

---

.github/workflows/test-go-gin.yml
.github/workflows/test-java-spark.yml
.github/workflows/test-java-spring.yml
.github/workflows/test-nodejs-express.yml
.github/workflows/test-php-slim.yml
.github/workflows/test-python-flask.yml
.gitignore
java-spring/Makefile
java-spring/build.gradle
nodejs-express/package.json
nodejs-express/server.js
php-slim/composer.json
python-flask/app.py
python-flask/pyproject.toml
python-flask/requirements-dev.txt
requirements.txt

A few patches have been submitted by Dependabot, but we don't have any means to validate them, other than doing it manually. This patch follows the spirit of GH-150, by adding more CI jobs for a few other projects.

Improve CI configuration

---

java-spring/build.gradle

Bundle a few Java PRs into one.
- GH-184
- GH-185
- GH-186
- GH-187
- GH-188

Java/Spring: Update to 3.2.1

---

java-spring/build.gradle

Bundles a few other PRs by Dependabot.
- GH-196
- GH-197
- GH-198
- GH-199
- GH-200

Update to Spring 3.2.2

---

java-spring/build.gradle

Bundle a few Dependabot PRs into a single one.
- GH-247
- GH-248
- GH-249
- GH-250
- GH-251

Dependencies: Update to Spring 3.3.0 in /java-spring

---

java-spring/build.gradle

Bundles a few other PRs submitted by Dependabot.
- GH-257
- GH-258
- GH-259
- GH-260
- GH-261

Java: Update to Spring Boot 3.3.1
